# Generated by Django 4.1 on 2022-08-15 10:11

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_address',
            field=models.CharField(blank=True, max_length=160, verbose_name='Address of Event Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_attendees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=50, verbose_name='Event Attendees'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location_lognitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_max_participant_num',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Maximum Participant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_publsihed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('742e3aa3-b300-40e1-8f13-dc51132517e1')),
        ),
    ]
