# Generated by Django 4.1 on 2022-08-15 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_event_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_publish_end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_url_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('6134a681-a4ed-4264-ab8e-745f3dfc7a93')),
        ),
    ]
