# Generated by Django 4.1 on 2022-08-20 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_publsihed_date',
            new_name='event_published_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('d14831e7-8f14-4eb3-9956-733c61502efa')),
        ),
    ]
