# Generated by Django 4.1 on 2022-08-20 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_rename_event_publsihed_date_event_event_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('54131c70-9c49-4a71-8a05-7f47456b038b')),
        ),
    ]
