# Generated by Django 4.1 on 2022-08-27 11:40

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_event_owner_alter_event_event_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_attendees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Event Attendees'), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('36c05bb0-7a1d-4eae-87c2-edae01de2b31')),
        ),
    ]
