# Generated by Django 4.1 on 2022-09-28 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_event_attendees_alter_event_event_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuthTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('refresh_token', models.CharField(blank=True, max_length=100, null=True)),
                ('token_expire_time', models.DateTimeField()),
                ('expire_in', models.IntegerField()),
                ('token_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('scope', models.CharField(blank=True, max_length=250, null=True)),
                ('token_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location_type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('onsite', 'Onsite')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('f9ceecf8-291d-4b82-baaf-a7ff44db732a')),
        ),
    ]
