# Generated by Django 4.1 on 2022-09-28 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_outhtokenmodel_alter_event_event_location_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outhtokenmodel',
            old_name='expire_in',
            new_name='expires_in',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('a0eaa45e-5eb6-47a9-b712-a69e73d959f9')),
        ),
    ]
