# Generated by Django 4.1 on 2022-09-28 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_expire_in_outhtokenmodel_expires_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('0f550d86-5f3a-4f18-8cd2-0cc97d8e8e89')),
        ),
        migrations.AlterField(
            model_name='outhtokenmodel',
            name='access_token',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='outhtokenmodel',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outhtokenmodel',
            name='token_owner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='outhtokenmodel',
            name='token_provider',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='outhtokenmodel',
            name='token_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
