# Generated by Django 4.1 on 2022-09-29 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_rename_event_date_event_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.UUID('27672a7e-c56c-4ca8-9395-75aab13ae73c')),
        ),
    ]
